language: python
cache: bundler
python:
  - "3.6"
install:
  # Install the latest release of Vale:
  - curl -sfL https://install.goreleaser.com/github.com/ValeLint/vale.sh | sh -s v2.10.5
  - export PATH="./bin:$PATH"
  - vale -v

  - bundle install --jobs=3

  - pip install yamllint
  - pip install markdata
  - pip install pyyaml
before_script:
  - yamllint -c '.yamllint.yml' alex
script:
  - cucumber
  - zip -r alex.zip alex -x "*.DS_Store"
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: alex.zip
  skip_cleanup: true
  on:
    tags: true
